baseURL = "https://homeboyc.cn/"
languageCode = "zh-cn"
title = "宅男的天台"
theme = "cocoa-hugo-theme"
builddrafts = false
canonifyurls = true
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[permalinks]
blog  = "blog/:slug/"

[[menu.main]]
name                   = "博客"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "关于"
weight                 = -110
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = "友链"
weight                 = -100
identifier             = "friendLinks"
url                    = "/friendLinks/"

[params]
paginate               = 10
include_rss            = true                          # include RSS <link> tag in <head> and show RSS icon
latestpostscount       = 5                             # how many posts to display on the home page
i18n_flags             = false                         # whether to display small country flags for available translations
author                 = "asjdf"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "宅男的天台 asjdf的博客"
email                  = "homeboyc@foxmail.com"
# extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
faviconfile            = "img/leaf.ico"
github                 = "//github.com/asjdf"
ICP                    = "闽ICP备2021002495号"           # 域名备案
beian                  = "闽公网安备 35030302354429号"   # 公安网备
# instagram              = "//instagram.com/you"
# px500                  = "//500px.com/username"
lang                   = "zh"
# linkedin               = "//linkedin.com/in/you"
noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
selfintro              = "一只在杭电摸鱼的小火鸡"        # appears in the site header when set to a non-empty string
# twitter                = "//twitter.com/you"
# mastodon               = "//example.com/@you"
# telegram               = "//t.me/you"

highlightjs            = true
# highlightjslanguages = ["go"]                        # additional languages not included in the "common" set
# highlightjsStyle     = "darcula"
# highlightjs_url        = "/js/highlight.min.js"        # relative path to your self hosted highlight.js file 
# highlightjs_css_url    = "css/default.min.css"         # relative path to your self hosted css config for highlight.js

piwik                  = false                         # If true, Piwik integration is enabled
# piwik_url            = "//www.example.com/piwik/"    # URL to your Piwik installation. Must End with a slash
# piwik_id             = 2                             # Id of your site in Piwik

gitalk                 = true
# if gitalk is true, the following params should be set. These parameters could be retrieved from github OAuth
gitalk_clientID        = "d567ff8bc4759c154b84"
gitalk_clientSecret    = "27dd2e23ddf976cdd24f41d668b18401bb593a86"
gitalk_repo            = "hugo.asjdf.io"
gitalk_owner           = "asjdf"
gitalk_admin           = ['asjdf']

favicon                = "/favicon.png"
avatar                 = "img/avatar.jpg" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
# gravatar             = ""                # gravatar hash. see https://en.gravatar.com/site/implement/hash/. do not use in the same time as avatar

# The following are DEPRECATED.
# gatracker              = "XYZ" # use googleAnalytics instead
# initials               = "ad"  # displayed on single post page; deprecated in v0.3.0.